export const SHOW_DATA_MENUS = 'SHOW_DATA_MENUS'
export const ADD_DATA_MENUS = 'ADD_DATA_MENUS'
export const ADD_DATA_ORDER = 'ADD_DATA_ORDER'
export const EDIT_DATA_MENUS = 'EDIT_DATA_MENUS'
export const DELETE_DATA_MENUS = 'DELETE_DATA_MENUS'

export const SHOW_DATA_ORDERS = 'SHOW_DATA_ORDERS'
export const EDIT_DATA_ORDERS = 'EDIT_DATA_ORDERS'
export const DELETE_DATA_ORDERS = 'DELETE_DATA_ORDERS'

export const UPDATE_QTY = 'UPDATE_QTY'